from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


MODELSCOPE_REPO = "Mark42IRPC/Minimax-H3-int8-fl2va-onnx-50CLIPS"
GITHUB_REPO = "https://github.com/MARK42IRPC/MinimaxH3-ONNX"


@dataclass(frozen=True)
class DownloadComponent:
    id: str
    label: str
    relative_path: str
    include: tuple[str, ...]
    role: str
    required_for_generation: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "relative_path": self.relative_path,
            "role": self.role,
            "required_for_generation": self.required_for_generation,
        }


DOWNLOAD_COMPONENTS: tuple[DownloadComponent, ...] = (
    DownloadComponent("qwen", "Qwen 文本编码器", "onnx_models/qwen3vl_32b_minimax_h3_nvfp4_awq", ("qwen3vl_32b_minimax_h3_nvfp4_awq/**",), "text_encoder", True),
    DownloadComponent("streaming", "FL2VA 流式基座版", "onnx_models/minimax_h3_fl2va_pruned_fp8_scaled_streaming", ("minimax_h3_fl2va_pruned_fp8_scaled_streaming/**",), "fl2va_transformer", True),
    DownloadComponent("video_vae", "Video VAE", "onnx_models/video_vae", ("video_vae/**",), "video_vae", True),
    DownloadComponent("audio_vae", "Audio VAE", "onnx_models/audio_vae", ("audio_vae/**",), "audio_vae", True),
    DownloadComponent("tokenizer", "H3 Tokenizer", "qwen_tokenizer", ("qwen_tokenizer/**",), "tokenizer", True),
)

_BY_ID = {item.id: item for item in DOWNLOAD_COMPONENTS}


def component_by_id(component_id: str) -> DownloadComponent:
    try:
        return _BY_ID[component_id]
    except KeyError as exc:
        raise ValueError(f"Unknown model component: {component_id}") from exc


def _manifest_status(directory: Path) -> dict[str, Any]:
    manifest_path = directory / "manifest.json"
    if not manifest_path.is_file():
        return {"status": "missing", "manifest": False, "missing_files": []}
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return {"status": "invalid", "manifest": True, "error": str(exc), "missing_files": []}
    graphs = manifest.get("graphs", [])
    missing = [str(item) for item in graphs if not (directory / str(item)).is_file()]
    # Some manifests use a block list while graph names are generated by the
    # exporter. The declared graph references remain the authoritative check.
    valid = manifest.get("validation_passed") is True
    if missing:
        status = "incomplete"
    elif not valid:
        status = "unvalidated"
    else:
        status = "ready"
    files = list(directory.rglob("*")) if directory.is_dir() else []
    size = sum(item.stat().st_size for item in files if item.is_file())
    return {
        "status": status,
        "manifest": True,
        "validation_passed": valid,
        "missing_files": missing,
        "graph_count": len(graphs),
        "size_bytes": size,
    }


def component_status(workspace: Path, item: DownloadComponent) -> dict[str, Any]:
    directory = workspace / item.relative_path
    if item.id == "tokenizer":
        required = ("tokenizer.json", "tokenizer_config.json", "vocab.json", "merges.txt")
        missing = [name for name in required if not (directory / name).is_file()]
        files = [directory / name for name in required if (directory / name).is_file()]
        size = sum(path.stat().st_size for path in files)
        return {**item.to_dict(), "status": "ready" if not missing else "incomplete", "manifest": False, "missing_files": missing, "size_bytes": size}
    return {**item.to_dict(), **_manifest_status(directory)}


def all_component_status(workspace: Path) -> list[dict[str, Any]]:
    return [component_status(workspace, item) for item in DOWNLOAD_COMPONENTS]
